//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WebEntityFramework.Models
{
    #region 컨텍스트
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    public partial class TaskDBEntities : ObjectContext
    {
        #region 생성자
    
        /// <summary>
        /// 응용 프로그램 구성 파일의 'TaskDBEntities' 섹션에서 검색된 연결 문자열을 사용하여 새 TaskDBEntities 개체를 초기화합니다.
        /// </summary>
        public TaskDBEntities() : base("name=TaskDBEntities", "TaskDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 새 TaskDBEntities 개체를 초기화합니다.
        /// </summary>
        public TaskDBEntities(string connectionString) : base(connectionString, "TaskDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 새 TaskDBEntities 개체를 초기화합니다.
        /// </summary>
        public TaskDBEntities(EntityConnection connection) : base(connection, "TaskDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 부분 메서드(Partial Method)
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        public ObjectSet<TaskList> TaskLists
        {
            get
            {
                if ((_TaskLists == null))
                {
                    _TaskLists = base.CreateObjectSet<TaskList>("TaskLists");
                }
                return _TaskLists;
            }
        }
        private ObjectSet<TaskList> _TaskLists;

        #endregion
        #region AddTo 메서드
    
        /// <summary>
        /// TaskLists EntitySet에 새 개체를 추가하는 데 사용되지 않는 메서드입니다. 연결된 ObjectSet&lt;T&gt; 속성의 .Add 메서드를 대신 사용하십시오.
        /// </summary>
        public void AddToTaskLists(TaskList taskList)
        {
            base.AddObject("TaskLists", taskList);
        }

        #endregion
    }
    

    #endregion
    
    #region 엔터티
    
    /// <summary>
    /// 사용 가능한 메타데이터 설명서가 없습니다.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TaskModel", Name="TaskList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TaskList : EntityObject
    {
        #region 팩터리 메서드
    
        /// <summary>
        /// 새 TaskList 개체를 만듭니다.
        /// </summary>
        /// <param name="listId">ListId 속성의 초기 값입니다.</param>
        /// <param name="isComplete">IsComplete 속성의 초기 값입니다.</param>
        /// <param name="priority">Priority 속성의 초기 값입니다.</param>
        /// <param name="dateCreated">DateCreated 속성의 초기 값입니다.</param>
        public static TaskList CreateTaskList(global::System.Int32 listId, global::System.Boolean isComplete, global::System.Int32 priority, global::System.DateTime dateCreated)
        {
            TaskList taskList = new TaskList();
            taskList.ListId = listId;
            taskList.IsComplete = isComplete;
            taskList.Priority = priority;
            taskList.DateCreated = dateCreated;
            return taskList;
        }

        #endregion
        #region 기본 속성
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ListId
        {
            get
            {
                return _ListId;
            }
            set
            {
                if (_ListId != value)
                {
                    OnListIdChanging(value);
                    ReportPropertyChanging("ListId");
                    _ListId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ListId");
                    OnListIdChanged();
                }
            }
        }
        private global::System.Int32 _ListId;
        partial void OnListIdChanging(global::System.Int32 value);
        partial void OnListIdChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsComplete
        {
            get
            {
                return _IsComplete;
            }
            set
            {
                OnIsCompleteChanging(value);
                ReportPropertyChanging("IsComplete");
                _IsComplete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsComplete");
                OnIsCompleteChanged();
            }
        }
        private global::System.Boolean _IsComplete;
        partial void OnIsCompleteChanging(global::System.Boolean value);
        partial void OnIsCompleteChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private global::System.Int32 _Priority;
        partial void OnPriorityChanging(global::System.Int32 value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// 사용 가능한 메타데이터 설명서가 없습니다.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();

        #endregion
    
    }

    #endregion
    
}
